static const char* xim_protocol_name[] = {
    "XIM_UNKNOWN",                           /*  0 */
    "XIM_CONNECT",                           /*  1 */
    "XIM_CONNECT_REPLY",                     /*  2 */
    "XIM_DISCONNECT",                        /*  3 */
    "XIM_DISCONNECT_REPLY",                  /*  4 */
    "XIM_UNKNOWN",                           /*  5 */
    "XIM_UNKNOWN",                           /*  6 */
    "XIM_UNKNOWN",                           /*  7 */
    "XIM_UNKNOWN",                           /*  8 */
    "XIM_UNKNOWN",                           /*  9 */
    "XIM_AUTH_REQUIRED",                     /* 10 */
    "XIM_AUTH_REPLY",                        /* 11 */
    "XIM_AUTH_NEXT",                         /* 12 */
    "XIM_AUTH_SETUP",                        /* 13 */
    "XIM_AUTH_NG",                           /* 14 */
    "XIM_UNKNOWN",                           /* 15 */
    "XIM_UNKNOWN",                           /* 16 */
    "XIM_UNKNOWN",                           /* 17 */
    "XIM_UNKNOWN",                           /* 18 */
    "XIM_UNKNOWN",                           /* 19 */
    "XIM_ERROR",                             /* 20 */
    "XIM_UNKNOWN",                           /* 21 */
    "XIM_UNKNOWN",                           /* 22 */
    "XIM_UNKNOWN",                           /* 23 */
    "XIM_UNKNOWN",                           /* 24 */
    "XIM_UNKNOWN",                           /* 25 */
    "XIM_UNKNOWN",                           /* 26 */
    "XIM_UNKNOWN",                           /* 27 */
    "XIM_UNKNOWN",                           /* 28 */
    "XIM_UNKNOWN",                           /* 29 */
    "XIM_OPEN",                              /* 30 */
    "XIM_OPEN_REPLY",                        /* 31 */
    "XIM_CLOSE",                             /* 32 */
    "XIM_CLOSE_REPLY",                       /* 33 */
    "XIM_REGISTER_TRIGGERKEYS",              /* 34 */
    "XIM_TRIGGER_NOTIFY",                    /* 35 */
    "XIM_TRIGGER_NOTIFY_REPLY",              /* 36 */
    "XIM_SET_EVENT_MASK",                    /* 37 */
    "XIM_ENCODING_NEGOTIATION",              /* 38 */
    "XIM_ENCODING_NEGOTIATION_REPLY",        /* 39 */
    "XIM_QUERY_EXTENSION",                   /* 40 */
    "XIM_QUERY_EXTENSION_REPLY",             /* 41 */
    "XIM_SET_IM_VALUES",                     /* 42 */
    "XIM_SET_IM_VALUES_REPLY",               /* 43 */
    "XIM_GET_IM_VALUES",                     /* 44 */
    "XIM_GET_IM_VALUES_REPLY",               /* 45 */
    "XIM_UNKNOWN",                           /* 46 */
    "XIM_UNKNOWN",                           /* 47 */
    "XIM_UNKNOWN",                           /* 48 */
    "XIM_UNKNOWN",                           /* 49 */
    "XIM_CREATE_IC",                         /* 50 */
    "XIM_CREATE_IC_REPLY",                   /* 51 */
    "XIM_DESTROY_IC",                        /* 52 */
    "XIM_DESTROY_IC_REPLY",                  /* 53 */
    "XIM_SET_IC_VALUES",                     /* 54 */
    "XIM_SET_IC_VALUES_REPLY",               /* 55 */
    "XIM_GET_IC_VALUES",                     /* 56 */
    "XIM_GET_IC_VALUES_REPLY",               /* 57 */
    "XIM_SET_IC_FOCUS",                      /* 58 */
    "XIM_UNSET_IC_FOCUS",                    /* 59 */
    "XIM_FORWARD_EVENT",                     /* 60 */
    "XIM_SYNC",                              /* 61 */
    "XIM_SYNC_REPLY",                        /* 62 */
    "XIM_COMMIT",                            /* 63 */
    "XIM_RESET_IC",                          /* 64 */
    "XIM_RESET_IC_REPLY",                    /* 65 */
    "XIM_UNKNOWN",                           /* 66 */
    "XIM_UNKNOWN",                           /* 67 */
    "XIM_UNKNOWN",                           /* 68 */
    "XIM_UNKNOWN",                           /* 69 */
    "XIM_GEOMETRY",                          /* 70 */
    "XIM_STR_CONVERSION",                    /* 71 */
    "XIM_STR_CONVERSION_REPLY",              /* 72 */
    "XIM_PREEDIT_START",                     /* 73 */
    "XIM_PREEDIT_START_REPLY",               /* 74 */
    "XIM_PREEDIT_DRAW",                      /* 75 */
    "XIM_PREEDIT_CARET",                     /* 76 */
    "XIM_PREEDIT_CARET_REPLY",               /* 77 */
    "XIM_PREEDIT_DONE",                      /* 78 */
    "XIM_STATUS_START",                      /* 79 */
    "XIM_STATUS_DRAW",                       /* 80 */
    "XIM_STATUS_DONE",                       /* 81 */
};
